### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by dzerrenner** [thoughtnirvana/xmldict#7]
The script does not work in python 3 because dict.iteritems was removed. I replaced `dict.iteritems()` with `dict.items()` in my clone (see [here](https://github.com/dzerrenner/xmldict/commit/ea30f0fa84f9d61a47b4ebc0571cdff3f625d014#diff-352bf759d5769275578d48f42e372089)). Works fine with that, but the tests faile, because the order of dictionary items is nor specified.

Here is my test output:

```
F.F.....
======================================================================
FAIL: test_dict_to_xml_attributes (__main__.TestXmlutils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 99, in test_dict_to_xml_attributes
    self.assertEqual(expected, dict_to_xml(dict_xml))
AssertionError: '<messages><message foo="bar1"><baz>baz1</baz>message1</message><message foo="ba [truncated]... != '<messages><flag>true</flag><message foo="bar1"><baz>ba
z1</baz>message1</message [truncated]...
- <messages><message foo="bar1"><baz>baz1</baz>message1</message><message foo="bar2"><baz>baz2</baz>message2</message><flag>true</flag></messages>
?                                                                                                                        -----------------
+ <messages><flag>true</flag><message foo="bar1"><baz>baz1</baz>message1</message><message foo="bar2"><baz>baz2</baz>message2</message></messages>
?            +++++++++++++++++


======================================================================
FAIL: test_dict_to_xml_lists (__main__.TestXmlutils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 90, in test_dict_to_xml_lists
    self.assertEqual(expected, dict_to_xml(dict_xml))
AssertionError: '<messages><message>message1</message><message>message2</message><flag>true</fla [truncated]... != '<messages><flag>true</flag><message>message1</message>
<message>message2</messag [truncated]...
- <messages><message>message1</message><message>message2</message><flag>true</flag></messages>
?                                                                  -----------------
+ <messages><flag>true</flag><message>message1</message><message>message2</message></messages>
?          +++++++++++++++++


----------------------------------------------------------------------
Ran 8 tests in 0.017s

FAILED (failures=2)
```

I don't wanna change the tests until i got some feedback about that.

**Comment by sandeep-gh** [comment]
Having the same issue.
